@startuml CapaPersistencia2



class  Empleado #palegreen;line:green;text:green{
    String dni
    String nss
    String telefono
    String nombre
    String apellidos
    Date fechaNac

}

class EmpleadoViñedos #palegreen;line:green;text:green{
    String user
    String pass
    Rol rol 
} 
enum Rol #palegreen;line:green;text:green{
ADMIN
CAPATAZ
CAPATAZ_TRACTORISTA
}



' note left of EmpleadoViñedos
' Son empleados durante todo el año. 
' Solo estos tendran acceso a la aplicacion.
' end note

' note left of Rol
'     CAPATA_TRACTORISTA puede desempeñar tareas de <b>tractorista</b>,
'     pero tambien de <b>capataz</b>
' end note

class TrabajadorVendimia #OrangeRed;line:Red;text:White{

}
' note right of TrabajadorVendimia
'     Son empleados <b>solo durante la campaña</b>,
'      y de disponibilidad muy variable
' end note

class DisponibilidadDiaria #OrangeRed;line:Red;text:White{
    DateTime horaDeEntrada
    DateTime horaDeSalida
    Date Dia
}



EmpleadoViñedos -up-|> Empleado
TrabajadorVendimia -up-|>Empleado

EmpleadoViñedos -down- Rol

TrabajadorVendimia "1" -down->  "0..*" DisponibilidadDiaria : "Dias disponibles de trabajo"

EmpleadoViñedos "1" -right- "0..*" TrabajadorVendimia :    "   Administra    "


@enduml