@startuml CapaPersistencia1


class Zona #palegreen;line:green;text:green {
    String nombre
    int metrosCuadrados
    String descripcion
    Formacion formacion
    String referenciaCatastral
}

enum Formacion #palegreen;line:green;text:green{
    EMPARRADO
    ESPALDERA
}

note as N1
    El Administrador crea y edita zonas y 
    lineas en cualquier momento del año .
    Durante la campaña se trabajan esas 
    lineas y se hace seguimiento del
    trabajo realizado en estas
end note
class Linea #palegreen;line:green;text:green{
    int numeroLinea
    int longitud
    Date fechaPlantacion
    boolean recoleccionHabilitada
}

class TipoVid #palegreen;line:green;text:green{
    String nombre
    int añosMaduracion
    String descripcion
}

class TrabajadorVendimia #palegreen;line:green;text:green{
    boolean inTask;
}


class Tarea #palegreen;line:green;text:green{
    DateTime horaEntradaLinea
    DateTime horaSalidaLinea    
    String comentarios
    TipoDeTrabajo tipoTrabajo
}

Enum TipoDeTrabajo #palegreen;line:green;text:green{
    LIMPIEZA
    PODA
    RECOLECCION
    CARGA

}

class Campaña #palegreen;line:green;text:green{
    Date inicioCampaña
    Date finalizacionCampaña
    int año
    Fase fase

}

class LineaCampaña #palegreen;line:green;text:green{
    Estado estado
    int porcentajeTrabajado
    boolean cargaLista
    Datetime finalizacionLimpieza
    Datetime finalizacionPoda
    Datetime finalizacionRecoleccion
    Datetime finalizacionCarga
}

enum Estado #palegreen;line:green;text:green{
    PAUSADO
    TRABAJANDO
    FINALIZADA
}

enum Fase #palegreen;line:green;text:green{
    LIMPIEZA
    PODA
    RECOLECCION_CARGA
}


class ZonaCampaña #palegreen;line:green;text:green{
    
}


class EmpleadoViñedos #palegreen;line:green;text:green{
}

class Tractor #palegreen;line:green;text:green{
    String marca
    String modelo
    String matricula
    int cargaMaxima
    int capacidadCajas
}

class UsoDeTractor #palegreen;line:green;text:green{
    
}
 

Zona -- Formacion 

Tarea "0..*" -up- "0..*" Tractor : > Se usa en 

(Tarea,Tractor) ..  UsoDeTractor

EmpleadoViñedos "1" -- "0..*" Tarea : Asigna Trabajador >
note right on link
    Un capataz o tractorista
    asigna a un trabajador de vendimia 
    a un trabajo pendiente en linea.
end note

EmpleadoViñedos "1  "-right- "0..*" Campaña : Administrador Inicia >

TrabajadorVendimia "0..*" -- "0..*" Tarea : Trabaja >
note top on link
    Un Capata puede hacer tareas de limpieza 
    sin necesidad de un trabajador de vendimia
end note


' EmpleadoViñedos "1" -- "0..*" Zona : administra >

Zona "1" *-- "1..*" Linea
Linea "*" -- "1" TipoVid


Tarea "1..*" --  "1" LineaCampaña

Tarea -right- TipoDeTrabajo

Linea "1" --  "0..*" LineaCampaña
Zona "1" -- "0..*"  ZonaCampaña 

LineaCampaña -- Estado

Campaña "1" *-- "1..*" ZonaCampaña
ZonaCampaña *-- "1..*" LineaCampaña 

Campaña -- Fase




' Problema: Que pasa si una linea es deshabilitada a mitad de campaña? DEBE DESHABILITARSE de la campaña si no se hizo recoleccion. PROBAR ESTO

@enduml
