@startuml CapaPersistencia1


class Zona {
    String nombre
    int metrosCuadrados
    String descripcion
    String referenciaCatastral
    

}

note as N1
    El Administrador crea y edita zonas y 
    lineas en cualquier momento del año .
    Durante la campaña se trabajan esas 
    lineas y se hace seguimiento del
    trabajo realizado en estas
end note
class Linea {
    int numeroLinea
    int longitud
    Date fechaPlantacion
    String tipoFormacion
    boolean recoleccionHabilitada
}

class TipoVid{
    String nombre
    int añosMaduracion
    String descripcion
}

class TrabajadorVendimia{

}


class TrabajoEnLinea{
    DateTime horaEntradaLinea
    DateTime horaSalidaLinea
    String comentarios
    TipoDeTrabajo tipoTrabajo
}

Enum TipoDeTrabajo{
    LIMPIEZA
    PODA
    RECOLECCION
    CARGA

}

class Campaña{
    Date inicioCampaña
    Date finalizacionCampaña
    int año

}

class LineaCampaña{
    Estado estado
    int cajasObtenidas
}

enum Estado{
    RECOLECCION_DESHABILITADA
    SIN_EMPEZAR
    PAUSADO
    LIMPIANDO
    RECOLECTANDO
    RECOGIENDO
    FINALIZADA
}
note right of Estado
    El estado nos proporcionara el estado actual 
    de una linea durante la campaña
    PODRIA DIVIDIRLO EN DOS? 
        Estados(SIN_EMPEZAR,, PAUSADO, FINALIZADA)
         y EstadosProgreso( LIMPIANDO, RECOLECTANDO, RECOGIENDO)
         RECOLECCION_DESHABILITADA no creo que me haga falta
end note

class ZonaCampaña{
    
}


class EmpleadoViñedos{
}

class Tractor{
    String marca
    String modelo
    String matricula
    int cargaMaxima
    int capacidadCajas
}

class UsoDeTractor{
    
}
 

TrabajoEnLinea "0..*" -up- "0..*" Tractor : > Se usa en 

(TrabajoEnLinea,Tractor) ..  UsoDeTractor

EmpleadoViñedos "1" -- "0..*" TrabajoEnLinea : Asigna Trabajador >
note right on link
    Un capataz o tractorista
    asigna a un trabajador de vendimia 
    a una linea y se genera
    un TrabajoEnLinea
end note

EmpleadoViñedos "1  "-right- "0..*" Campaña : Administrador Inicia >

TrabajadorVendimia "0..*" -- "0..*" TrabajoEnLinea : Trabaja >
note top on link
    Un Capata puede hacer tareas de limpieza 
    sin necesidad de un trabajador de vendimia
end note


' EmpleadoViñedos "1" -- "0..*" Zona : administra >

Zona "1" *-- "1..*" Linea
Linea "*" -- "1" TipoVid


TrabajoEnLinea "1..*" --  "1" LineaCampaña

TrabajoEnLinea -right- TipoDeTrabajo

Linea "1" --  "0..*" LineaCampaña
Zona "1" -- "0..*"  ZonaCampaña 

LineaCampaña -- Estado

Campaña "1" *-- "1..*" ZonaCampaña
ZonaCampaña *-- "1..*" LineaCampaña 





' Problema: Que pasa si una linea es deshabilitada a mitad de campaña? DEBE DESHABILITARSE de la campaña si no se hizo recoleccion. PROBAR ESTO

@enduml
